### ISSUE TITLE
Worldgen snow persists on water and non-solid blocks.

### ISSUE THREAD

**Issue by Tokeli** [Virtuoel/Permafrost#1]
Don't know if this is even something fixable, but I've noticed that when there's 1-depth water, there is an occasional snow layer on top of it. It also will spawn on top of some plants  (Only the ones from the XL Food Mod that I've seen so far.)

**Comment by Virtuoel** [comment]
~~Not sure what you mean by the "1-depth water" part. Is this happening with normal Minecraft Water or some other mod's fluid? Can you post a screenshot of this?~~
~~Also, which versions of Forge and Permafrost are you running?~~

~~In terms of the XL Food Mod, is [this](https://minecraft.curseforge.com/projects/xl-food-mod) the mod you are referring to? It probably is an error on their side, as Permafrost changes just the light requirements for when Snow Layers form, which should not cause this.~~
~~I can try to look into the problem on their side if you let me know which of their plants are affected and which version of it you are running.~~

EDIT:
On second glance I see you mentioned Snow Layers placed during world generation. This is likely due to the way Permafrost disables the melting of Snow Layers and Ice by disabling their ticking, which probably also prevents them from popping off if in an invalid location. I will work on a quick fix for that tomorrow.

**Comment by Tokeli** [comment]
Wellp, sorry about that, should have done a little more research on my end first, it looks like it was another worldgen mod doing it instead! Switching to vanilla worldgen and the issues vanish. Sorry!

**Comment by Virtuoel** [comment]
Had some suspicions that it may have been related to a modded world generator as I had not run into this during testing. I guess this helped in finding the issue in whatever that mod was, so I suppose I'll not continue with my planned "fix" for this issue in the hopes that should the issue come up again, the generation problem can be forwarded to the mod doing the worldgen.
No need to be sorry. Thank you for the report.
